server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://${db_server}:5432/postgres?user=${db_username}&password=${db_user_password}&sslmode=require
    password: ${db_user_password}
    username: ${db_username}
#    driver-class-name: org.postgresql.Driver
#    password: discerneded
#    url: jdbc:postgresql://localhost:5432/discerneded
#    username: discerneded

  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: create-drop
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true


#  mail:
#    host: localhost
#    port: 1025
#    username: hello
#    password: hello
#
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: ${secret_jwt}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

#debug: true